wip: $range
transform-ts-community/transform-ts-contrib pull request #1
Opened 2020-09-13 09:56 UTC by rokoucha

2020-09-15 08:54 UTC, tosuke commented
anyなのが気になるな…ちゃんとしたレビューはあとでやる

2020-09-16 17:41 UTC, rokoucha commented
> 
> 
> anyなのが気になるな…ちゃんとしたレビューはあとでやる

string | number | any[] な transformer を受け取れるようにした

TODO: b7a9d9e は別 PR に cherry-pick する

2020-09-17 18:55 UTC, rokoucha commented
@tosuke 関係ないコミットを削除してテスト整備 rebase しました

2020-09-17 18:59 UTC, rinsuki commented on src/__tests__/transformers/range.test.ts
> +    expect($range($.number, {}).transform(1)).toEqual(error(ValidationError.from(new UndefinedRangeError())))
これ型で不可能にしたくない？って思ったけど難しそう

2020-09-17 18:59 UTC, rinsuki commented on src/transformers/range.ts
> +  return Transformer.from<number | string | Array<any>, A>(u => {
`{length: number}` とかでもいいのかなという気がした

2020-09-18 05:12 UTC, tosuke reviewed
@rokoucha レビュした

2020-09-18 05:12 UTC, tosuke commented on src/transformers/range.ts
> +): Transformer<number | string | Array<any>, A> {
`length`を持ってるオブジェクトなら何でも検証できるようにしたい。それと後続の`Transformer`は長くなりうるから引数の後ろに持ってきて
```ts
function $range<A extends number | { length: number }, B>({ min, max }, f: Transformer<A, B>): Transformer<A, B>
```
みたいにできそう？

2020-09-18 05:12 UTC, tosuke commented on src/transformers/range.ts
> +    if (!min && !max) return error(ValidationError.from(new UndefinedRangeError()))
`min`か`max`どちらかがあることを要求するなら引数の型を`{ min: number; max?: number } | { min?: number; max: number }`とかにしてほしい

2020-09-18 05:12 UTC, tosuke commented on src/transformers/range.ts
> +    if (min && max && max < min) return error(ValidationError.from(new InvalidRangeError(min, max)))
min/max自体のエラーは`ValidationError`でないのでTransformer返す前に例外投げるとかのほうがよさそう

2020-09-18 05:13 UTC, tosuke commented on src/transformers/range.ts
> +    if (!min && !max) return error(ValidationError.from(new UndefinedRangeError()))
それと、`0`もfalsyなのでこのコードは正しくないと思う。`==null`で判定してほしい

2020-09-18 13:08 UTC, rokoucha commented on src/__tests__/transformers/range.test.ts
> +    expect($range($.number, {}).transform(1)).toEqual(error(ValidationError.from(new UndefinedRangeError())))
https://github.com/transform-ts/contrib/pull/1#discussion_r490704818 で解決できたのでそのようにした

2020-09-18 13:09 UTC, rokoucha commented on src/transformers/range.ts
> +    if (min && max && max < min) return error(ValidationError.from(new InvalidRangeError(min, max)))
throw するようにした

2020-09-18 13:09 UTC, rokoucha commented on src/transformers/range.ts
> +    if (!min && !max) return error(ValidationError.from(new UndefinedRangeError()))
引数の型を union にして undefined かどうかを判定するようにした

2020-09-18 13:31 UTC, rokoucha commented on src/transformers/range.ts
> +): Transformer<number | string | Array<any>, A> {
https://github.com/transform-ts/contrib/blob/36bbeed14ee25b0cfa1f091d05eca83524a9835b/src/transformers/range.ts#L42 でやってみたけど `typeof u === 'number'` の上で `else if` してるのに `u` が `A extends number | { length: number}` のままで typegurad が効かない…
ていうかこの式は

2020-09-18 13:32 UTC, rokoucha commented on src/transformers/range.ts
> +): Transformer<number | string | Array<any>, A> {
`const c: number | { length: number } = u` してあげるとちゃんと型がつくのでそれで対応した

2020-09-18 13:32 UTC, rokoucha commented on src/transformers/range.ts
> +  return Transformer.from<number | string | Array<any>, A>(u => {
https://github.com/transform-ts/contrib/pull/1#discussion_r490951595

2020-09-18 14:11 UTC, tosuke requested changes
@rokoucha すまないけどもう少し言うことがあった。修正頼む

2020-09-18 14:11 UTC, tosuke commented on src/transformers/range.ts
> +    if (max && max < length) return error(ValidationError.from(new OufOfMaxError(length, max)))
こっちもundefined判定しなさーい

2020-09-18 14:11 UTC, tosuke commented on src/transformers/range.ts
> +      throw new InvalidRangeError(min, max)
この節自体を`return Transformer`の外に持ってきてほしい。できるだけ早めに間違った引数を渡してることに気付けるように

2020-09-18 14:19 UTC, rinsuki commented on src/__tests__/transformers/range.test.ts
> +})
min/max片方しかない時のテストなくない？

2020-09-18 14:19 UTC, rinsuki commented on src/transformers/range.ts
> +    else length = c.length
ブロックのほうがわかりやすいと思う

2020-09-18 14:45 UTC, rokoucha commented on src/__tests__/transformers/range.test.ts
> +})
639f810 でちょっと改善してみた(手抜き)

2020-09-19 13:30 UTC, rinsuki approved these changes

2020-09-20 10:13 UTC, tosuke approved these changes

2020-09-20 10:19 UTC, merged